---
title: "flat_full.Rmd for working package"
output: html_document
editor_options: 
  chunk_output_type: console
---

<!-- Run this 'development' chunk -->
<!-- Store every call to library() that you need to explore your functions -->

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.

If it is the first time you use {fusen}, after 'description', you can directly run the last chunk of the present file with inflate() inside.
--> 

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```


<!-- 
 Store your dataset in a directory named "inst/" at the root of your project.
 Use it for your tests in this Rmd thanks to `pkgload::load_all()` to make it available
and `system.file()` to read it in your examples.

- There already is a dataset in the "inst/" directory to be used in the examples below
-->

```{r development-dataset}
# Run all this chunk in the console directly
# There already is a dataset in the "inst/" directory
# Make the dataset file available to the current Rmd during development
pkgload::load_all(path = here::here(), export_all = FALSE)

# You will be able to read your example data file in each of your function examples and tests as follows - see chunks below
datafile <- system.file("iris.csv", package = "ggsmatr")
iris <- read.csv(datafile, encoding = "UTF-8")
```


# ggsmatr: Example using iris dataset

<!--
Create a chunk for the core of the function

- The chunk needs to be named `function` at least
- It contains the code of a documented function
- The chunk can also be named `function-my_median` to make it easily
findable in your Rmd
- Let the `@examples` part empty, and use the next `examples` chunk instead to present reproducible examples

After inflating the template

-  This function code will automatically be added in a new file in the "R/" directory
-->


```{r function}
#' ggsmatr 'ggplot2' based SMATR plots
#'
#' Create a scatter plot based on the coefficients from (Standardised) Major Axis Estimation fit.
#' @usage ggsmatr(data, groups, xvar, yvar, sma.fit, ci = FALSE, ci.alpha = 0.2, n = 100)
#' @param data a dataframe.
#' @param groups group variable.
#' @param xvar x variable for drawing.
#' @param yvar y variable for drawing.
#' @param sma.fit an sma or ma object fitted in SMATR package.
#' @param ci logical. If TRUE, add a parametric confidence ribbon for the SMA slope, using the slope confidence intervals stored in `sma.fit` (set the level with `sma(..., alpha = )`). Given that SMA lines pass through the group centroid, the ribbon is a slope-CI envelope pivoted at each group mean, and it is not related with the OLS band of `geom_smooth()`. Default is FALSE.
#' @param ci.alpha Alpha transparency passed to [ggplot2::geom_ribbon()]. Default is 0.2.
#' @param n Number of x values at which the confidence ribbon is evaluated in each group. Default is 100.
#'
#' @return ggplot based plot of sma.
#' @export
ggsmatr <- function(data, groups, xvar, yvar, sma.fit, ci = FALSE, ci.alpha = 0.2, n = 100){



  x.var <- rlang::sym(xvar)
  y.var <- rlang::sym(yvar)
  grp <- rlang::sym(groups)
  ngrps<- length(unique(data[[groups]]))

  # as factors, function from Tlamatini package
  as_factorALL<- function(dataframe){

    df<- dataframe
    df[sapply(df, is.character)] <- lapply(df[sapply(df, is.character)],
                                           as.factor)
    return(df)
  }

  data<- as_factorALL(data)
  data<- stats::na.omit(data)
  # define colors
  grps.df = unique(data[[groups]])
  station_cols = scales::hue_pal()(length(grps.df))
  names(station_cols) <- unique(data[[groups]])

  fitsall <- sma.fit$groupsummary |> dplyr::select(group , r2, pval, Slope, Int)
  fitsall <- fitsall |>  dplyr::mutate_if(is.numeric, round, digits = 3)
  fitsall


  # extraer coeficientes de SMA, vars:  dataframe  groups   xvar
  bb <- data.frame(stats::coef(sma.fit))

  bb <- bb |>
    tibble::rownames_to_column(var = "group")

  # calcular minimo y maximo del eje x para cada sitio
  bb2 <- data |> 
    dplyr::select(groups, xvar) |>  
    dplyr::group_by(.data[[groups]]) |>
    dplyr::summarise(dplyr::across(.cols = xvar,
                                   .fns = list(min = min, max = max),
                                   .names = "{fn}_x"))
  names(bb2)[1] <- 'group'


  #unir dataframe
  bb3 <- base::merge(bb,bb2, by= "group")

  #calcular min y max de y con intercepto y elevacion
  bb4 <- bb3 |>
    dplyr::mutate(min_y = (slope*min_x) + elevation) |>
    dplyr::mutate(max_y = (slope*max_x) + elevation)

  df.pl <- cbind(bb4, fitsall[,-1])

  if (isTRUE(ci)) {
    print(sma.fit$groupsummary |>
            dplyr::select(group, r2, pval, Slope, Slope_lowCI, Slope_highCI) |>
            dplyr::mutate_if(is.numeric, round, digits = 3))
  } else {
    print(df.pl[, c("group", "r2", "pval")])
  }

  df.ci <- NULL
  if (isTRUE(ci)) {
    ci_cols <- c("Slope_lowCI", "Slope_highCI")
    if (is.null(sma.fit$groupsummary) || !all(ci_cols %in% names(sma.fit$groupsummary))) {
      stop("sma.fit$groupsummary does not contain slope confidence intervals.", call. = FALSE)
    }

    cents <- data |>
      dplyr::group_by(.data[[groups]]) |>
      dplyr::summarise(
        xbar = mean(.data[[xvar]], na.rm = TRUE),
        ybar = mean(.data[[yvar]], na.rm = TRUE),
        .groups = "drop"
      )
    names(cents)[1] <- "group"

    cis <- sma.fit$groupsummary[, c("group", "Slope", "Slope_lowCI", "Slope_highCI")]
    ci_df <- merge(merge(cis, cents, by = "group"), bb2, by = "group")

    df.ci <- do.call(rbind, lapply(seq_len(nrow(ci_df)), function(i) {
      xseq <- seq(ci_df$min_x[i], ci_df$max_x[i], length.out = n)
      xseq <- sort(unique(c(xseq, ci_df$xbar[i])))
      y_low <- ci_df$ybar[i] + ci_df$Slope_lowCI[i] * (xseq - ci_df$xbar[i])
      y_high <- ci_df$ybar[i] + ci_df$Slope_highCI[i] * (xseq - ci_df$xbar[i])
      data.frame(
        group = as.character(ci_df$group[i]),
        x = xseq,
        ymin = pmin(y_low, y_high),
        ymax = pmax(y_low, y_high),
        stringsAsFactors = FALSE
      )
    }))
    grp_levels <- if (is.factor(data[[groups]])) levels(data[[groups]]) else unique(as.character(data[[groups]]))
    df.ci$group <- factor(df.ci$group, levels = grp_levels)
  }

  ggp <-  ggplot2::ggplot(data = data, ggplot2::aes(x = !! x.var,
                                                    y = !! y.var,
                                                    color= !! grp,
                                                    fill= !! grp))

  if (isTRUE(ci)) {
    ggp <- ggp +
      ggplot2::geom_ribbon(
        data = df.ci,
        mapping = ggplot2::aes(x = x, ymin = ymin, ymax = ymax, fill = group),
        alpha = ci.alpha,
        colour = NA,
        inherit.aes = FALSE,
        show.legend = FALSE
      )
  }

  ggp <- ggp +
    ggplot2::geom_point(size=2, alpha = 0.5) +
    ggplot2::geom_segment(data = df.pl ,ggplot2::aes(x= min_x, xend= max_x, y=min_y, yend=max_y, colour= group),inherit.aes = FALSE, size= 1)


  .GlobalEnv$ggp <- ggp


  return(ggp)

}
```





<!--
Create a chunk with an example of use for your function

- The chunk needs to be named `examples` at least
- It contains working examples of your function
- The chunk is better be named `examples-my_median` to be handled
correctly when inflated as a vignette

After inflating the template

-  This example will automatically be added in the '@examples' part of our function above in the "R/" directory
- This example will automatically be added in the vignette created from this Rmd template
-->

```{r examples}
datafile <- system.file("iris.csv", package = "ggsmatr")
df.iris <- read.csv(datafile, encoding = "UTF-8")

library(ggsmatr)
library(ggplot2)
library(smatr)
fit <- sma(Sepal.Length ~ Sepal.Width + Species,
           data = df.iris, shift = TRUE, elev.test = TRUE, alpha = 0.05)

ggsmatr(data = df.iris, groups = "Species",
        xvar = "Sepal.Width", yvar = "Sepal.Length",
        sma.fit = fit) +
  theme(legend.position = "top", legend.title = element_blank()) +
  ylab("Sepal.Length") +
  xlab("Sepal.Width")

# parametric slope-CI ribbon, using the intervals already stored in the sma fit
ggsmatr(data = df.iris, groups = "Species",
        xvar = "Sepal.Width", yvar = "Sepal.Length",
        sma.fit = fit, ci = TRUE) +
  theme(legend.position = "top", legend.title = element_blank()) +
  ylab("Sepal.Length") +
  xlab("Sepal.Width")
```


<!--
Create a chunk with a test of use for your function

- The chunk needs to be named `tests` at least
- It contains working tests of your function
- The chunk is better be named `tests-my_median` to be handled
correctly when inflated as a vignette

After inflating the template

-  This test code will automatically be added in the "tests/testthat/" directory
-->

```{r tests}
# Test with your dataset in "inst/"
datafile <- system.file("iris.csv", package = "ggsmatr")
df.iris <- read.csv(datafile, encoding = "UTF-8")

library(ggsmatr)
library(ggplot2)
library(smatr)
fit = sma(Sepal.Length ~ Sepal.Width + Species, data = df.iris,shift=TRUE, elev.test=TRUE)

test_that("ggsmatr works properly and show error if needed", {
 expect_visible(ggsmatr(data =  df.iris, groups = "Species", xvar =  "Sepal.Width", yvar = "Sepal.Length", sma.fit =  fit))
  expect_error(ggsmatr(data =  df.iris, groups = "Species", xvar =  "Sepal.Width", yvar = "Sepal.Length"))
})

test_that("ggsmatr adds a parametric slope-CI ribbon when ci = TRUE", {
  p_default <- ggsmatr(data = df.iris, groups = "Species", xvar = "Sepal.Width",
                       yvar = "Sepal.Length", sma.fit = fit)
  geoms_default <- vapply(p_default$layers, function(l) class(l$geom)[1], character(1))
  expect_false("GeomRibbon" %in% geoms_default)

  p_ci <- ggsmatr(data = df.iris, groups = "Species", xvar = "Sepal.Width",
                  yvar = "Sepal.Length", sma.fit = fit, ci = TRUE)
  geoms_ci <- vapply(p_ci$layers, function(l) class(l$geom)[1], character(1))
  expect_true("GeomRibbon" %in% geoms_ci)

  rib <- p_ci$layers[[which(geoms_ci == "GeomRibbon")[1]]]$data
  expect_true(all(rib$ymin <= rib$ymax))

  for (g in unique(as.character(rib$group))) {
    xbar <- mean(df.iris$Sepal.Width[as.character(df.iris$Species) == g], na.rm = TRUE)
    d <- rib[as.character(rib$group) == g, , drop = FALSE]
    i <- which.min(abs(d$x - xbar))
    expect_equal(unname(d$ymax[i] - d$ymin[i]), 0, tolerance = 1e-8)
  }
})

```


<!--
# There can be development actions

Create a chunk with 'development' actions

- The chunk needs to be named `development` or `dev`
- It contains functions that are used for package development only
- Note that you may want to store most of these functions in the 0-dev_history.Rmd file

These are only included in the present flat template file, their content will not be part of the package anywhere else.
-->

```{r development-inflate, eval=FALSE}
# Keep eval=FALSE to avoid infinite loop in case you hit the knit button
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_full.Rmd", vignette_name = "ggsmatr example", check = TRUE)
```

