# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

# Test with your dataset in "inst/"
datafile <- system.file("iris.csv", package = "ggsmatr")
df.iris <- read.csv(datafile, encoding = "UTF-8")

library(ggsmatr)
library(ggplot2)
library(smatr)
fit = sma(Sepal.Length ~ Sepal.Width + Species, data = df.iris,shift=TRUE, elev.test=TRUE)

test_that("ggsmatr works properly and show error if needed", {
 expect_visible(ggsmatr(data =  df.iris, groups = "Species", xvar =  "Sepal.Width", yvar = "Sepal.Length", sma.fit =  fit))
  expect_error(ggsmatr(data =  df.iris, groups = "Species", xvar =  "Sepal.Width", yvar = "Sepal.Length"))
})

test_that("ggsmatr adds a parametric slope-CI ribbon when ci = TRUE", {
  p_default <- ggsmatr(data = df.iris, groups = "Species", xvar = "Sepal.Width",
                       yvar = "Sepal.Length", sma.fit = fit)
  geoms_default <- vapply(p_default$layers, function(l) class(l$geom)[1], character(1))
  expect_false("GeomRibbon" %in% geoms_default)

  p_ci <- ggsmatr(data = df.iris, groups = "Species", xvar = "Sepal.Width",
                  yvar = "Sepal.Length", sma.fit = fit, ci = TRUE)
  geoms_ci <- vapply(p_ci$layers, function(l) class(l$geom)[1], character(1))
  expect_true("GeomRibbon" %in% geoms_ci)

  rib <- p_ci$layers[[which(geoms_ci == "GeomRibbon")[1]]]$data
  expect_true(all(rib$ymin <= rib$ymax))

  for (g in unique(as.character(rib$group))) {
    xbar <- mean(df.iris$Sepal.Width[as.character(df.iris$Species) == g], na.rm = TRUE)
    d <- rib[as.character(rib$group) == g, , drop = FALSE]
    i <- which.min(abs(d$x - xbar))
    expect_equal(unname(d$ymax[i] - d$ymin[i]), 0, tolerance = 1e-8)
  }
})

