# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' ggsmatr 'ggplot2' based SMATR plots
#'
#' Create a scatter plot based on the coefficients from (Standardised) Major Axis Estimation fit.
#' @usage ggsmatr(data, groups, xvar, yvar, sma.fit, ci = FALSE, ci.alpha = 0.2, n = 100)
#' @param data a dataframe.
#' @param groups group variable.
#' @param xvar x variable for drawing.
#' @param yvar y variable for drawing.
#' @param sma.fit an sma or ma object fitted in SMATR package.
#' @param ci logical. If TRUE, add a parametric confidence ribbon for the SMA slope, using the slope confidence intervals stored in `sma.fit` (set the level with `sma(..., alpha = )`). Given that SMA lines pass through the group centroid, the ribbon is a slope-CI envelope pivoted at each group mean, and it is not related with the OLS band of `geom_smooth()`. Default is FALSE.
#' @param ci.alpha Alpha transparency passed to [ggplot2::geom_ribbon()]. Default is 0.2.
#' @param n Number of x values at which the confidence ribbon is evaluated in each group. Default is 100.
#'
#' @return ggplot based plot of sma.
#' @export
#' @examples
#' datafile <- system.file("iris.csv", package = "ggsmatr")
#' df.iris <- read.csv(datafile, encoding = "UTF-8")
#'
#' library(ggsmatr)
#' library(ggplot2)
#' library(smatr)
#' fit <- sma(Sepal.Length ~ Sepal.Width + Species,
#'            data = df.iris, shift = TRUE, elev.test = TRUE, alpha = 0.05)
#'
#' ggsmatr(data = df.iris, groups = "Species",
#'         xvar = "Sepal.Width", yvar = "Sepal.Length",
#'         sma.fit = fit) +
#'   theme(legend.position = "top", legend.title = element_blank()) +
#'   ylab("Sepal.Length") +
#'   xlab("Sepal.Width")
#'
#' # parametric slope-CI ribbon, using the intervals already stored in the sma fit
#' ggsmatr(data = df.iris, groups = "Species",
#'         xvar = "Sepal.Width", yvar = "Sepal.Length",
#'         sma.fit = fit, ci = TRUE) +
#'   theme(legend.position = "top", legend.title = element_blank()) +
#'   ylab("Sepal.Length") +
#'   xlab("Sepal.Width")
#'
#'
ggsmatr <- function(data, groups, xvar, yvar, sma.fit, ci = FALSE, ci.alpha = 0.2, n = 100){



  x.var <- rlang::sym(xvar)
  y.var <- rlang::sym(yvar)
  grp <- rlang::sym(groups)
  ngrps<- length(unique(data[[groups]]))

  # as factors, function from Tlamatini package
  as_factorALL<- function(dataframe){

    df<- dataframe
    df[sapply(df, is.character)] <- lapply(df[sapply(df, is.character)],
                                           as.factor)
    return(df)
  }

  data<- as_factorALL(data)
  data<- stats::na.omit(data)
  # define colors
  grps.df = unique(data[[groups]])
  station_cols = scales::hue_pal()(length(grps.df))
  names(station_cols) <- unique(data[[groups]])

  fitsall <- sma.fit$groupsummary |> dplyr::select(group , r2, pval, Slope, Int)
  fitsall <- fitsall |>  dplyr::mutate_if(is.numeric, round, digits = 3)
  fitsall


  # extraer coeficientes de SMA, vars:  dataframe  groups   xvar
  bb <- data.frame(stats::coef(sma.fit))

  bb <- bb |>
    tibble::rownames_to_column(var = "group")

  # calcular minimo y maximo del eje x para cada sitio
  bb2 <- data |> 
    dplyr::select(groups, xvar) |>  
    dplyr::group_by(.data[[groups]]) |>
    dplyr::summarise(dplyr::across(.cols = xvar,
                                   .fns = list(min = min, max = max),
                                   .names = "{fn}_x"))
  names(bb2)[1] <- 'group'


  #unir dataframe
  bb3 <- base::merge(bb,bb2, by= "group")

  #calcular min y max de y con intercepto y elevacion
  bb4 <- bb3 |>
    dplyr::mutate(min_y = (slope*min_x) + elevation) |>
    dplyr::mutate(max_y = (slope*max_x) + elevation)

  df.pl <- cbind(bb4, fitsall[,-1])

  if (isTRUE(ci)) {
    print(sma.fit$groupsummary |>
            dplyr::select(group, r2, pval, Slope, Slope_lowCI, Slope_highCI) |>
            dplyr::mutate_if(is.numeric, round, digits = 3))
  } else {
    print(df.pl[, c("group", "r2", "pval")])
  }

  df.ci <- NULL
  if (isTRUE(ci)) {
    ci_cols <- c("Slope_lowCI", "Slope_highCI")
    if (is.null(sma.fit$groupsummary) || !all(ci_cols %in% names(sma.fit$groupsummary))) {
      stop("sma.fit$groupsummary does not contain slope confidence intervals.", call. = FALSE)
    }

    cents <- data |>
      dplyr::group_by(.data[[groups]]) |>
      dplyr::summarise(
        xbar = mean(.data[[xvar]], na.rm = TRUE),
        ybar = mean(.data[[yvar]], na.rm = TRUE),
        .groups = "drop"
      )
    names(cents)[1] <- "group"

    cis <- sma.fit$groupsummary[, c("group", "Slope", "Slope_lowCI", "Slope_highCI")]
    ci_df <- merge(merge(cis, cents, by = "group"), bb2, by = "group")

    df.ci <- do.call(rbind, lapply(seq_len(nrow(ci_df)), function(i) {
      xseq <- seq(ci_df$min_x[i], ci_df$max_x[i], length.out = n)
      xseq <- sort(unique(c(xseq, ci_df$xbar[i])))
      y_low <- ci_df$ybar[i] + ci_df$Slope_lowCI[i] * (xseq - ci_df$xbar[i])
      y_high <- ci_df$ybar[i] + ci_df$Slope_highCI[i] * (xseq - ci_df$xbar[i])
      data.frame(
        group = as.character(ci_df$group[i]),
        x = xseq,
        ymin = pmin(y_low, y_high),
        ymax = pmax(y_low, y_high),
        stringsAsFactors = FALSE
      )
    }))
    grp_levels <- if (is.factor(data[[groups]])) levels(data[[groups]]) else unique(as.character(data[[groups]]))
    df.ci$group <- factor(df.ci$group, levels = grp_levels)
  }

  ggp <-  ggplot2::ggplot(data = data, ggplot2::aes(x = !! x.var,
                                                    y = !! y.var,
                                                    color= !! grp))

  if (isTRUE(ci)) {
    ggp <- ggp +
      ggplot2::geom_ribbon(
        data = df.ci,
        mapping = ggplot2::aes(x = x, ymin = ymin, ymax = ymax, fill = group),
        alpha = ci.alpha,
        colour = NA,
        inherit.aes = FALSE,
        show.legend = FALSE
      )
  }

  ggp <- ggp +
    ggplot2::geom_point(size=2, alpha = 0.5) +
    ggplot2::geom_segment(data = df.pl ,ggplot2::aes(x= min_x, xend= max_x, y=min_y, yend=max_y, colour= group),inherit.aes = FALSE, size= 1)


  .GlobalEnv$ggp <- ggp


  return(ggp)

}
