# WARNING - Generated by {fusen} from dev/flat_additional.Rmd: do not edit by hand # nolint: line_length_linter.

#' global functions - do not run
#'
#' Global functions
#' @noRd
#'
utils::globalVariables(c(".data", "Int", "Slope","Slope_lowCI","Slope_highCI","elevation","group","max_x", "max_y","min_x", "xmin", "min_y", "pval", "r2", "slope","coef","x","ymin","ymax","xbar","ybar"))
