# WARNING - Generated by {fusen} from /dev/flat_additional.Rmd: do not edit by hand

#' global functions - do not run
#'
#' Global functions
#' @return nothing
#' @keywords internal
#' @export
#'
utils::globalVariables(c(".data", "Int", "Slope","elevation","group","max_x", "max_y","min_x", "xmin", "min_y", "pval", "r2", "slope","coef"))
